name: Deploy pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.4.0
      
    - name: Docker login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        push: true
        tags: |
          joaopedrogama/employees-api:${{ github.sha }}
          joaopedrogama/employees-api:latest
          
  deploy:
    needs: build-and-deploy-artifact
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Docker login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Set permissions for private key
      run: |
        echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
        
    - name: Pull Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-229-141-72.sa-east-1.compute.amazonaws.com 'sudo docker pull your-dockerhub-username/cddemo:latest'
        
    - name: Stop running container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-229-141-72.sa-east-1.compute.amazonaws.com 'sudo docker stop employees-api || true'
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-229-141-72.sa-east-1.compute.amazonaws.com 'sudo docker rm employees-api || true'
    
    - name: Run new container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-229-141-72.sa-east-1.compute.amazonaws.com 'sudo docker run -d --name cddemo -p 8080:8080 joaopedrogama/employees-api:latest'
