name: Deploy pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Docker login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        push: true
        tags: |
          joaopedrogama/employees-api:${{ github.sha }}
          joaopedrogama/employees-api:latest
          
  deploy:
    needs: build-and-deploy-artifact
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Docker
        run: sudo docker stop joaopedrogama/employees-api:latest

      - name: Pull Docker
        run: sudo docker pull joaopedrogama/employees-api:latest

      - name: Run Docker
        run: sudo docker run -d -p 80:8080 joaopedrogama/employees-api:latest
