name: Deploy pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.4.0
      
    - name: Docker login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        push: true
        tags: |
          joaopedrogama/employees-api:${{ github.sha }}
          joaopedrogama/employees-api:latest
          
  deploy:
    needs: build-and-deploy-artifact
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Docker login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: deploy 
      uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5.8
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_default_region: sa-east-1c
        dot_env: ${{ secrets.DOT_ENV }}
        ec2_instance_type: t2.micro
